language: node_js
node_js:
  - Its/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
  - yarn cname
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于 Travis 南你的库送码，在 Travis 的项目战置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master
